### ISSUE TITLE
Tweak color of message displayed after signing up for the mailing list

### ISSUE THREAD

**Issue by jcfr** [freepn/freepn_marketing_website#5]
After signing to the mailing list, the text is orange. This is of course consistent with the branding but the orange color initially throw me off and made me think something failed.

What about using "green" color for the check mark ?

![image](https://user-images.githubusercontent.com/219043/74275628-3abce800-4ce2-11ea-9f5f-6e369a08a064.png)

**Comment by ian-bateman** [comment]
Hmm that is a fair point - don't want people to be confused - will see what looks good and update the colors in my next commit 😄
